# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SubmoduleTestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SubmoduleTestProject

  target 'SubmoduleTestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SubmoduleTestProjectUITests' do
    # Pods for testing
  end

end
